# Generated by Django 5.1.6 on 2025-03-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
